-- Initial schema (PostgreSQL), generated from the JPA entities by Hibernate 6.6 at v0.1.0.
-- Constraint names match what ddl-auto=update produced, so databases created before Flyway was
-- introduced can be baselined at version 1 (spring.flyway.baseline-on-migrate) without changes.


create table badges (
    earned_at timestamp(6),
    id bigint generated by default as identity,
    user_id bigint not null,
    description varchar(255) not null,
    icon varchar(255) not null,
    name varchar(255) not null,
    primary key (id)
);

create table chat_messages (
    id bigint generated by default as identity,
    timestamp timestamp(6),
    user_id bigint not null,
    content TEXT not null,
    role varchar(255) not null,
    primary key (id)
);

create table coach_memories (
    expires_at date,
    importance_score integer not null,
    reference_date date,
    created_at timestamp(6),
    id bigint generated by default as identity,
    user_id bigint not null,
    content TEXT not null,
    type varchar(255) not null check (type in ('DAILY_SUMMARY','USER_INSIGHT','LONG_TERM_FACT')),
    primary key (id)
);

create table goals (
    end_date date,
    start_date date,
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    user_id bigint not null,
    description varchar(255),
    name varchar(255) not null,
    status varchar(255),
    primary key (id)
);

create table habit_completions (
    completed_at timestamp(6) not null,
    habit_id bigint not null,
    id bigint generated by default as identity,
    primary key (id)
);

create table habits (
    is_active boolean not null,
    created_at timestamp(6),
    goal_id bigint,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    user_id bigint not null,
    cue_habit_stack varchar(255),
    cue_implementation_intention varchar(255),
    frequency_json TEXT,
    name varchar(255) not null,
    two_minute_version varchar(255),
    primary key (id)
);

create table login_history (
    id bigint generated by default as identity,
    login_time timestamp(6),
    user_id bigint not null,
    browser varchar(255),
    device_info varchar(255),
    device_type varchar(255),
    ip_address varchar(255),
    location varchar(255),
    operating_system varchar(255),
    status varchar(255),
    primary key (id)
);

create table mood_logs (
    created_at timestamp(6),
    id bigint generated by default as identity,
    user_id bigint not null,
    mood_type varchar(255) not null,
    note varchar(255),
    primary key (id)
);

create table refresh_tokens (
    created_at timestamp(6),
    expiry_date timestamp(6) not null,
    id bigint generated by default as identity,
    user_id bigint,
    browser varchar(255),
    device_id varchar(255),
    device_info varchar(255),
    device_type varchar(255),
    ip_address varchar(255),
    location varchar(255),
    operating_system varchar(255),
    token varchar(255) not null unique,
    primary key (id)
);

create table user_roles (
    user_id bigint not null,
    role varchar(255)
);

create table users (
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    email varchar(255) not null unique,
    identity_statement varchar(255),
    password varchar(255) not null,
    primary key (id)
);

create table weekly_reviews (
    best_streak integer,
    current_streak integer not null,
    total_completed integer not null,
    created_at timestamp(6),
    id bigint generated by default as identity,
    user_id bigint not null,
    highlights_json TEXT not null,
    raw_response TEXT,
    suggestion TEXT not null,
    primary key (id)
);

alter table if exists badges 
   add constraint FK6xty094p6yob3kcweag7yv6c8 
   foreign key (user_id) 
   references users;

alter table if exists chat_messages 
   add constraint FK6f0y4l43ihmgfswkgy9yrtjkh 
   foreign key (user_id) 
   references users;

alter table if exists coach_memories 
   add constraint FK7gy5i2k26iupvsvuoyytt5fic 
   foreign key (user_id) 
   references users;

alter table if exists goals 
   add constraint FKb1mp6ulyqkpcw6bc1a2mr7v1g 
   foreign key (user_id) 
   references users;

alter table if exists habit_completions 
   add constraint FKdt8vmlabmctme9yn5fbnp9ipf 
   foreign key (habit_id) 
   references habits;

alter table if exists habits 
   add constraint FKjeuc8h34b3hire0wlw4ou9w3m 
   foreign key (goal_id) 
   references goals;

alter table if exists habits 
   add constraint FKg3n2qqwmsyv3517xdcosouk9i 
   foreign key (user_id) 
   references users;

alter table if exists login_history 
   add constraint FK20v0mimmdegh2afs39uixlxpm 
   foreign key (user_id) 
   references users;

alter table if exists refresh_tokens 
   add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
   foreign key (user_id) 
   references users;

alter table if exists user_roles 
   add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
   foreign key (user_id) 
   references users;

alter table if exists weekly_reviews 
   add constraint FKl5ikxrv39gruh5b3yb6kwodqg 
   foreign key (user_id) 
   references users;
